import { el, styleElement, type Attrs } from "../svg/elements.js";
import { escapeXml } from "../svg/escape.js";
import { computeAnchors, VIEWBOX_SIZE } from "./geometry.js";
import { mixHex } from "./palettes.js";
import { buildDefs } from "./defs.js";
import { renderBackground } from "./background.js";
import { createRng, deriveSeed } from "../seed/rng.js";
import { seedFingerprint } from "../seed/hash.js";
import type { Seed128 } from "../seed/hash.js";
import { familyById, JITTER_OFFSET, SALT } from "../traits/families.js";
import type { TraitSelection } from "../traits/select.js";
import {
  animationCss,
  reducedMotionCss,
  ANIMATION_PRESETS,
} from "../animation/animations.js";
import type { AnimationId } from "../animation/animations.js";
import type { StyleDefinition } from "../style/styles.js";
import type { AvatarColors, RenderContext } from "../traits/types.js";

// fully resolved, validated render input
export interface RenderOptions {
  readonly seed128: Seed128;
  readonly normalizedSeed: string;
  readonly selection: TraitSelection;
  readonly style: StyleDefinition;
  readonly animations: ReadonlySet<string>;
  readonly speed: number;
  readonly size: number | undefined;
  readonly title: string | undefined;
  readonly desc: string | undefined;
  readonly decorative: boolean;
  readonly background: {
    readonly mode: "auto" | "none" | "transparent" | "solid" | "gradient";
    readonly color?: string;
    readonly from?: string;
    readonly to?: string;
  };
}

// hook helper: families may skip layers entirely
function callHook(
  familyId: Parameters<typeof familyById>[0],
  hook: "main" | "back" | "body" | "head" | "face" | "front",
  ctx: RenderContext,
  id: string,
): string {
  const fn = familyById(familyId).hooks[hook];
  return fn === undefined ? "" : fn(ctx, id as never);
}

// any preset occupying the root level contributes the root css class
function hasRootMotion(animations: ReadonlySet<string>): boolean {
  for (const id of animations) {
    const preset = (
      ANIMATION_PRESETS as Record<
        string,
        { levels: readonly string[] } | undefined
      >
    )[id];
    if (preset !== undefined && preset.levels.includes("root")) return true;
  }
  return false;
}

// compose every layer into the final svg string, in fixed z-order
export function renderMonkey(opts: RenderOptions): string {
  const sel = opts.selection;
  const style = opts.style;
  const prefix = `mx${seedFingerprint(opts.seed128)}`;
  const anchors = computeAnchors(sel.head, sel.body);

  // resolve the background: explicit options win over the auto selection
  let bgColor = sel.backgroundColor;
  let bgStyle = sel.backgroundStyle;
  let bgFrom: string | null = null;
  if (opts.background.mode === "solid") {
    bgColor = opts.background.color ?? bgColor;
    bgStyle = "flat";
  } else if (opts.background.mode === "gradient") {
    bgFrom = opts.background.from ?? null;
    bgColor = opts.background.to ?? bgColor;
    bgStyle = "gradient";
  }

  const colors: AvatarColors = {
    ink: "#2e2620",
    white: "#ffffff",
    accent: sel.accent,
    hair: sel.hairColor,
    background: bgColor,
    backgroundLight: mixHex(bgColor, style.dark ? "#3a352e" : "#ffffff", 0.45),
    star: "#f0be4f",
    heart: "#e05a5a",
    tongue: "#e0766e",
    blush: "#e8927c",
  };

  // family-scoped render contexts; jitter streams sit above pick streams
  const extraCss: string[] = [];
  const ctxFor = (salt: number): RenderContext => ({
    rng: createRng(deriveSeed(opts.seed128, salt + JITTER_OFFSET)),
    palette: sel.palette,
    anchors,
    prefix,
    colors,
    selection: sel,
    animations: opts.animations,
    extraCss,
    speed: opts.speed,
    line: (base: number) => Math.round(base * style.lineWidth * 100) / 100,
    depth: style.depth,
    cap: style.cap,
    grad: (name: string) => `url(#${prefix}-${name})`,
  });

  // --- svg root + accessibility metadata ----------------------------------
  const attrs: Attrs = {
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: `0 0 ${VIEWBOX_SIZE} ${VIEWBOX_SIZE}`,
  };
  if (opts.size !== undefined) {
    attrs.width = opts.size;
    attrs.height = opts.size;
  }

  let meta = "";
  if (opts.decorative) {
    attrs["aria-hidden"] = "true";
    attrs.focusable = "false";
  } else {
    attrs.role = "img";
    attrs["aria-labelledby"] = `${prefix}-t ${prefix}-d`;
    const title = opts.title ?? `monkey avatar for "${opts.normalizedSeed}"`;
    const desc =
      opts.desc ??
      `deterministic monkey avatar generated by monkeyx from the seed "${opts.normalizedSeed}"`;
    meta =
      el("title", { id: `${prefix}-t` }, escapeXml(title)) +
      el("desc", { id: `${prefix}-d` }, escapeXml(desc));
  }

  // --- defs + background ---------------------------------------------------
  const defs = buildDefs({
    palette: sel.palette,
    accent: sel.accent,
    hairColor: sel.hairColor,
    depth: style.depth,
    prefix,
    glow: style.glow,
  });

  let background = "";
  if (
    opts.background.mode !== "none" &&
    opts.background.mode !== "transparent"
  ) {
    if (bgFrom !== null) {
      background =
        el(
          "defs",
          {},
          el(
            "radialGradient",
            { id: `${prefix}-bg`, cx: "50%", cy: "40%", r: "75%" },
            el("stop", { offset: "0%", "stop-color": bgFrom }) +
              el("stop", { offset: "100%", "stop-color": bgColor }),
          ),
        ) +
        el("rect", {
          x: 0,
          y: 0,
          width: VIEWBOX_SIZE,
          height: VIEWBOX_SIZE,
          fill: `url(#${prefix}-bg)`,
        });
    } else {
      background = renderBackground(ctxFor(SALT.backgroundColor), bgStyle);
    }
  }

  // --- character stages -----------------------------------------------------
  const shadow = el("ellipse", {
    cx: 128,
    cy: 238,
    rx: 54,
    ry: 6,
    fill: "#1f1b16",
    opacity: 0.1,
  });

  const extrasBack = callHook(
    "extra",
    "back",
    ctxFor(familyById("extra").salt),
    sel.extra,
  );
  const hairBack = callHook(
    "hair",
    "back",
    ctxFor(familyById("hair").salt),
    sel.hair,
  );
  const capeBack = callHook(
    "clothing",
    "back",
    ctxFor(familyById("clothing").salt),
    sel.clothing,
  );

  const tailMain = callHook(
    "tail",
    "main",
    ctxFor(familyById("tail").salt),
    sel.tail,
  );
  const tailGroup = opts.animations.has("tail")
    ? el("g", { class: `${prefix}-tail` }, tailMain)
    : tailMain;

  const legsCtx = ctxFor(familyById("legs").salt);
  const legs = callHook("legs", "main", legsCtx, sel.legs);
  const legsFront = callHook("legs", "front", legsCtx, sel.legs);
  const bodyMain = callHook(
    "body",
    "main",
    ctxFor(familyById("body").salt),
    sel.body,
  );
  const patternBody = callHook(
    "pattern",
    "body",
    ctxFor(familyById("pattern").salt),
    sel.pattern,
  );
  const arms = callHook(
    "arms",
    "main",
    ctxFor(familyById("arms").salt),
    sel.arms,
  );
  const clothing = callHook(
    "clothing",
    "main",
    ctxFor(familyById("clothing").salt),
    sel.clothing,
  );

  // head group internals, in z-order
  const ctxHair = ctxFor(familyById("hair").salt);
  const earsMain = callHook(
    "ears",
    "main",
    ctxFor(familyById("ears").salt),
    sel.ears,
  );
  const earsGroup = opts.animations.has("ears")
    ? el("g", { class: `${prefix}-ears` }, earsMain)
    : earsMain;
  const headMain = callHook(
    "head",
    "main",
    ctxFor(familyById("head").salt),
    sel.head,
  );
  const patternHead = callHook(
    "pattern",
    "head",
    ctxFor(familyById("pattern").salt),
    sel.pattern,
  );
  const facePatch = callHook(
    "head",
    "face",
    ctxFor(familyById("head").salt),
    sel.head,
  );
  const extraFace = callHook(
    "extra",
    "face",
    ctxFor(familyById("extra").salt),
    sel.extra,
  );
  const eyesGroup = el(
    "g",
    {
      class:
        opts.animations.has("blink") || opts.animations.has("double-blink")
          ? `${prefix}-eyes`
          : undefined,
    },
    callHook("eyes", "main", ctxFor(familyById("eyes").salt), sel.eyes),
  );
  const brows = callHook(
    "brows",
    "main",
    ctxFor(familyById("brows").salt),
    sel.brows,
  );
  const nose = callHook(
    "nose",
    "main",
    ctxFor(familyById("nose").salt),
    sel.nose,
  );
  const mouth = callHook(
    "mouth",
    "main",
    ctxFor(familyById("mouth").salt),
    sel.mouth,
  );
  const hairFront = callHook("hair", "main", ctxHair, sel.hair);
  const accessory = callHook(
    "accessory",
    "main",
    ctxFor(familyById("accessory").salt),
    sel.accessory,
  );

  const headChildren = [
    earsGroup,
    headMain,
    patternHead,
    facePatch,
    extraFace,
    eyesGroup,
    brows,
    nose,
    mouth,
    hairFront,
    accessory,
  ];

  // head-level css motion (idle tilt, nod) rides on the head class
  const headMotion = opts.animations.has("idle") || opts.animations.has("nod");
  const headGroup = el(
    "g",
    { class: headMotion ? `${prefix}-head` : undefined },
    ...headChildren,
  );

  const extrasFront = callHook(
    "extra",
    "front",
    ctxFor(familyById("extra").salt),
    sel.extra,
  );

  const character = [
    shadow,
    extrasBack,
    hairBack,
    capeBack,
    tailGroup,
    legs,
    bodyMain,
    patternBody,
    arms,
    clothing,
    legsFront,
    headGroup,
    extrasFront,
  ];

  // tiny style scales the whole character around a grounded pivot
  const wrapped =
    style.scale !== 1
      ? el(
          "g",
          {
            transform: `translate(${128 * (1 - style.scale)} ${152 * (1 - style.scale)}) scale(${style.scale})`,
          },
          ...character,
        )
      : character;

  // --- animation css ---------------------------------------------------------
  let styleEl = "";
  if (opts.animations.size > 0) {
    const ids = [...opts.animations].filter(
      (id) => id in ANIMATION_PRESETS,
    ) as AnimationId[];
    const css =
      (animationCss(prefix, ids, opts.speed) ?? "") + extraCss.join("");
    if (css !== "") styleEl = styleElement(`${css}${reducedMotionCss(prefix)}`);
  }

  const rootAttrs: Attrs = {
    class: hasRootMotion(opts.animations) ? `${prefix}-root` : undefined,
  };
  const rootGroup = el("g", rootAttrs, ...wrapped);

  return el("svg", attrs, meta, defs, background, rootGroup, styleEl);
}
